# Generated by Django 4.1.2 on 2023-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0004_alter_products_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=200),
        ),
    ]
