# Generated by Django 4.1.2 on 2023-02-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_products_image_alter_products_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=200),
        ),
    ]
